### ISSUE TITLE
Update PyPi

### ISSUE THREAD

**Issue by jeanollion** [MicroscPSF/MicroscPSF-Py#3]
Hello, 
Would is be possible to update the PyPi package, so that it contains the `gLXYZParticleScan` method ? 
Thanks in advance, 
Cordially, 
Jean Ollion

**Comment by HazenBabcock** [comment]
Yes, this is possible. I will try to get to this in the next few days.

**Comment by HazenBabcock** [comment]
I pushed the latest version, hopefully this works for you.

**Comment by jeanollion** [comment]
Hello Hazen, 
Yes it works, than you very much
Best Regards
Jean
